login:
    path: /login
    defaults: { _controller: FctBundle:Profesor:login }
    
registro:
    path: /registro
    defaults: { _controller: FctBundle:Profesor:registro }

login_check:
    path: /login_check

logout:
    path: /logout

perfil:
    path: /perfil/{nif}
    defaults: { _controller: FctBundle:Profesor:perfil, nif: ~ }

listado_prof:
    path: /listado_prof/{num_pag}/{per_pag}
    defaults: { _controller: FctBundle:Profesor:listado, num_pag:1 , per_pag:5}

delete_prof:
    path: /delete_prof/{nif}
    defaults: { _controller: FctBundle:Profesor:delete, nif: ~}

fct_homepage:
    path: /
    defaults: { _controller: FctBundle:Default:index }
    
panel_maestro:
    path: /panel
    defaults: { _controller: FctBundle:Profesor:panel_maestro}
    
funcion_panel:
    path: /panel/{id}/{numero}
    defaults: { _controller: FctBundle:Profesor:funcion_panel, id: ~, numero: ~}

