login:
    path: /login
    defaults: { _controller: FctBundle:Profesor:login }
    
registro:
    path: /registro
    defaults: { _controller: FctBundle:Profesor:registro }

login_check:
    path: /login_check

logout:
    path: /logout

perfil:
    path: /perfil/{nif}
    defaults: { _controller: FctBundle:Profesor:perfil, nif: ~ }
    
listado_prof:
    path: /listado_prof
    defaults: { _controller: FctBundle:Profesor:listado }

delete_prof:
    path: /delete_prof/{nif}
    defaults: { _controller: FctBundle:Profesor:delete, nif: ~}

fct_homepage:
    path:     /
    defaults: { _controller: FctBundle:Default:index }