#Inicio
fct_homepage:
    path: /
    defaults: { _controller: FctBundle:Default:index }
    

#XML profesor
serializador_profesor:
    path: /serializador/profesor
    defaults: { _controller: FctBundle:Profesor:serializador, _format: xml }
#XML alumno
serializador_alumno:
    path: /serializador/alumno
    defaults: { _controller: FctBundle:Alumno:serializador }
#XML ciclo
serializador_ciclo:
    path: /serializador/ciclo
    defaults: { _controller: FctBundle:Ciclo:serializador }
#XML empresa
serializador_empresa:
    path: /serializador/empresa
    defaults: { _controller: FctBundle:Empresa:serializador }
#XML fct
serializador_fct:
    path: /serializador/fct
    defaults: { _controller: FctBundle:Fct:serializador }



#Login
login:
    path: /login
    defaults: { _controller: FctBundle:Profesor:login }
#Check del login
login_check:
    path: /login_check
#Logout
logout:
    path: /logout
#Formulario de registro
registro:
    path: /registro
    defaults: { _controller: FctBundle:Profesor:registro }



#Panel maestro
panel_maestro:
    path: /panel
    defaults: { _controller: FctBundle:Profesor:panel_maestro}
#Funciones del panel maestro
funcion_panel:
    path: /panel/{id}/{numero}
    defaults: { _controller: FctBundle:Profesor:funcion_panel, id: ~, numero: ~}


### PROFESORES ###
#Perfil de profesor
perfil:
    path: /perfil/{nif}
    defaults: { _controller: FctBundle:Profesor:perfil, nif: ~ }
#Listado profesor
listado_prof:
    path: /listado_prof/{num_pag}/{per_pag}
    defaults: { _controller: FctBundle:Profesor:listado, num_pag:1 , per_pag:5}
#Borrado de profesor
delete_prof:
    path: /delete_prof/{nif}
    defaults: { _controller: FctBundle:Profesor:delete, nif: ~}


### ALUMNOS ###
#Perfil del alumno
ficha_alum:
    path: /ficha_alum/{nif}
    defaults: { _controller: FctBundle:Alumno:ficha, nif: ~ }
#Listado alumnos
listado_alum:
    path: /listado_alum/{num_pag}/{per_pag}
    defaults: { _controller: FctBundle:Alumno:listado, num_pag:1 , per_pag:5}
#Registro de alumnos
reg_alum:
    path: /reg_alum
    defaults: { _controller: FctBundle:Alumno:registro }
#Borrado de alumnos
delete_alum:
    path: /delete_alum/{nif}
    defaults: { _controller: FctBundle:Alumno:delete, nif: ~}
    
    
### EMPRESAS ###
#Perfil del empresa
ficha_emp:
    path: /ficha_emp/{cif}
    defaults: { _controller: FctBundle:Empresa:ficha, cif: ~ }
#Listado empresa
listado_emp:
    path: /listado_emp/{num_pag}/{per_pag}
    defaults: { _controller: FctBundle:Empresa:listado, num_pag:1 , per_pag:5}
#Registro de empresa
reg_emp:
    path: /reg_emp
    defaults: { _controller: FctBundle:Empresa:registro }
#Borrado de empresa
delete_emp:
    path: /delete_emp/{cif}
    defaults: { _controller: FctBundle:Empresa:delete, cif: ~}



### CICLOS ###
#Perfil del Ciclo
ficha_ciclo:
    path: /ficha_ciclo/{id}
    defaults: { _controller: FctBundle:Ciclo:ficha, id: ~}
#Listado Ciclos
listado_ciclo:
    path: /listado_ciclo/{id}
    defaults: { _controller: FctBundle:Ciclo:listado, id: ~}
#Registro de Ciclo
reg_ciclo:
    path: /reg_ciclo
    defaults: { _controller: FctBundle:Ciclo:registro }
#Borrado de Ciclo
delete_ciclo:
    path: /delete_ciclo/{id}
    defaults: { _controller: FctBundle:Ciclo:delete, id: ~}
    
    
### FCT ###
#Listado Fct
listado_fct:
    path: /listado_fct/{num_pag}/{per_pag}
    defaults: { _controller: FctBundle:Fct:listado, num_pag:1 , per_pag:5}
#Registro de Ciclo
reg_fct:
    path: /reg_fct
    defaults: { _controller: FctBundle:Fct:registro }
#Borrado de Ciclo
delete_fct:
    path: /delete_fct/{id}
    defaults: { _controller: FctBundle:Fct:delete, id: ~}