FctBundle\Entity\Profesor:
    properties:
        nif:
            - NotBlank: {message: "El nif está vacío."}
            - Regex:
                pattern: '/(([X-Z]{1})([-]?)(\d{7})([-]?)([A-Z]{1}))|((\d{8})([-]?)([A-Z]{1}))/'
                message: "El dni debe ser de 8 dígitos y 1 letra en mayúsculas."
        nombre:
            - NotBlank: {message: "El nombre está vacío."}
            - Regex:
                pattern: "/([a-zA-ZñÑáéíóúÁÉÍÓÚüÜ ']{3,30})/"
                message: "El nombre debe ser de 3 a 30 carácteres."
        ape1:
            - NotBlank: {message: "El 1º apellido está vacío."}
            - Regex:
                pattern: "/([a-zA-ZñÑáéíóúÁÉÍÓÚüÜ ']{3,30})/"
                message: "El 1º apellido debe ser de 3 a 30 carácteres."
        ape2:
            - NotBlank: {message: "El 2º apellido está vacío."}
            - Regex:
                pattern: "/([a-zA-ZñÑáéíóúÁÉÍÓÚüÜ ']{3,30})/"
                message: "El 2º apellido debe ser de 3 a 30 carácteres."
        nuser:
            - NotBlank: {message: "El nombre de usuario está vacío."}
            - Regex:
                pattern: '/([a-zA-Z]{8,20})/'
                message: "El nombre de usuario debe de ser de 8 a 20 carácteres sin espacios con letras mayúsculas o minusculas."
        pass:
            - NotBlank: {message: "La contraseña está vacía."}
            - Regex:
                pattern: '/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$/'
                message: "La contraseña debe de ser de 8 a 20 carácteres con al menos 1 dígito, 1 minúscula y 1 mayúscula"
        tlf:
            - NotBlank: {message: "El telefono está vacío."}
            - Regex:
                pattern: '/\d{9}/'
                message: "El telefono debe de ser de 9 dígitos."
        mail:
            - NotBlank: {message: "El email está vacío."}
            - Length:
                max: 50
                maxMessage: 'La longitud máxima del email es de 50 carácteres.'
            - Regex:
                pattern: '/\b[\w\.-]+@[\w\.-]+\.\w{2,4}\b/'
                message: "El email debe tener un formato correcto y como máximo 50 carácteres."
                
FctBundle\Entity\Alumno:
    properties:
        nif:
            - NotBlank: {message: "El nif está vacío."}
            - Regex:
                pattern: '/(([X-Z]{1})([-]?)(\d{7})([-]?)([A-Z]{1}))|((\d{8})([-]?)([A-Z]{1}))/'
                message: "El dni debe ser de 8 dígitos y 1 letra en mayúsculas."
        nombre:
            - NotBlank: {message: "El nombre está vacío."}
            - Regex:
                pattern: "/([a-zA-ZñÑáéíóúÁÉÍÓÚüÜ ']{3,30})/"
                message: "El nombre debe ser de 3 a 30 carácteres."
        ape1:
            - NotBlank: {message: "El 1º apellido está vacío."}
            - Regex:
                pattern: "/([a-zA-ZñÑáéíóúÁÉÍÓÚüÜ ']{3,30})/"
                message: "El 1º apellido debe ser de 3 a 30 carácteres."
        ape2:
            - NotBlank: {message: "El 2º apellido está vacío."}
            - Regex:
                pattern: "/([a-zA-ZñÑáéíóúÁÉÍÓÚüÜ ']{3,30})/"
                message: "El 2º apellido debe ser de 3 a 30 carácteres."
        direccion:
            - NotBlank: {message: "La dirección está vacía."}
            - Regex:
                pattern: "/([a-zA-ZñÑáéíóúÁÉÍÓÚüÜ1234567890º ']{10,50})/"
                message: "La dirección debe ser de 3 a 30 carácteres."
        poblacion:
            - NotBlank: {message: "La población está vacía."}
            - Regex:
                pattern: "/([a-zA-ZñÑáéíóúÁÉÍÓÚüÜ ']{3,30})/"
                message: "La poblacion debe ser de 3 a 30 carácteres."
        cp:
            - NotBlank: {message: "El código postal está vacío."}
            - Regex:
                pattern: "/[1234567890]{5}/"
                message: "El código postal debe de ser una serie de 5 dígitos."
        provincia:
            - NotBlank: {message: "La provincia está vacío."}
            - Regex:
                pattern: "/([a-zA-ZñÑáéíóúÁÉÍÓÚüÜ ']{3,30})/"
                message: "La provincia debe ser de 3 a 30 carácteres."
        tlf:
            - NotBlank: {message: "El telefono está vacío."}
            - Regex:
                pattern: '/\d{9}/'
                message: "El telefono debe de ser de 9 dígitos."
        mail:
            - NotBlank: {message: "El email está vacío."}
            - Length:
                max: 50
                maxMessage: 'La longitud máxima del email es de 50 carácteres.'
            - Regex:
                pattern: '/\b[\w\.-]+@[\w\.-]+\.\w{2,4}\b/'
                message: "El email debe tener un formato correcto y como máximo 50 carácteres."

FctBundle\Entity\Empresa:
    properties:
        cif:
            - NotBlank: {message: "El nif está vacío."}
            - Regex:
                pattern: '/(([X-Z]{1})([-]?)(\d{7})([-]?)([A-Z]{1}))|((\d{8})([-]?)([A-Z]{1}))/'
                message: "El CIF debe ser de 8 dígitos y 1 letra en mayúsculas."
        nombre:
            - NotBlank: {message: "El nombre está vacío."}
            - Regex:
                pattern: "/([a-zA-ZñÑáéíóúÁÉÍÓÚüÜ ']{3,30})/"
                message: "El nombre debe ser de 3 a 30 carácteres."
        direccion:
            - NotBlank: {message: "La dirección está vacía."}
            - Regex:
                pattern: "/([a-zA-ZñÑáéíóúÁÉÍÓÚüÜ1234567890º ']{10,50})/"
                message: "La dirección debe ser de 3 a 30 carácteres."
        poblacion:
            - NotBlank: {message: "La población está vacía."}
            - Regex:
                pattern: "/([a-zA-ZñÑáéíóúÁÉÍÓÚüÜ ']{3,30})/"
                message: "La poblacion debe ser de 3 a 30 carácteres."
        cp:
            - NotBlank: {message: "El código postal está vacío."}
            - Regex:
                pattern: "/[1234567890]{5}/"
                message: "El código postal debe de ser una serie de 5 dígitos."
        provincia:
            - NotBlank: {message: "La provincia está vacío."}
            - Regex:
                pattern: "/([a-zA-ZñÑáéíóúÁÉÍÓÚüÜ ']{3,30})/"
                message: "La provincia debe ser de 3 a 30 carácteres."
        tlf:
            - NotBlank: {message: "El telefono está vacío."}
            - Regex:
                pattern: '/\d{9}/'
                message: "El telefono debe de ser de 9 dígitos."
        mail:
            - NotBlank: {message: "El email está vacío."}
            - Length:
                max: 50
                maxMessage: 'La longitud máxima del email es de 50 carácteres.'
            - Regex:
                pattern: '/\b[\w\.-]+@[\w\.-]+\.\w{2,4}\b/'
                message: "El email debe tener un formato correcto y como máximo 50 carácteres."

FctBundle\Entity\Ciclo:
    properties:
        abr:
            - NotBlank: {message: "El nif está vacío."}
            - Regex:
                pattern: "/([A-ZÑÁÉÍÓÚÜ1234567890º ']{10,50})/"
                message: "La abrebiatura debe ser una serie de 2 a 10 carácteres(mayúsculas)."
        nombre:
            - NotBlank: {message: "El nombre está vacío."}
            - Regex:
                pattern: "/([a-zA-ZñÑáéíóúÁÉÍÓÚüÜ1234567890º ']{10,50})/"
                message: "El nombre debe ser de 10 a 50 carácteres."
        horas:
            - NotBlank: {message: "El código postal está vacío."}
            - Regex:
                pattern: "/[1234567890]{2,11}/"
                message: "Las horas deben de ser una serie de hasta 11 dígitos."