<?php

namespace FctBundle\Repository;

/**
 * FctRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FctRepository extends \Doctrine\ORM\EntityRepository
{
}
